fix: remove line break from url
coveo/cli pull request #479
Opened 2021-09-20 19:09 UTC by y-lakhdar

## Proposed changes

`cli.warn` formats the string given in parameter and injects line breaks based on the terminal width. That way it can prepend symbols at every lines (see [source code](https://github.com/oclif/errors/blob/master/src/errors/pretty-print.ts#L54)).

The proposed solution is to print the url with the `cli.log` instead of `cli.warn`. `cli.log` does not manipulate the string and ensures the uri is clickable even when it is wrapped.
![image](https://user-images.githubusercontent.com/12199712/134060137-414063ff-9661-4b25-a2b4-032a191f7bf7.png)

## Breaking changes

## Testing

- [ ] Unit Tests:

- [ ] Functionnal Tests:

- [x] Manual Tests:

2021-09-20 19:15 UTC, olamothe approved these changes

2021-09-20 19:15 UTC, olamothe commented on packages/cli/src/lib/errors/snapshotErrors.ts
> +  private synchronizationPlanUrl: string;
I'd suggest not adding stateful class member for something that can be re-computed very easily.

Suggestion: 
```
private get synchronizationPlanUrl() {
return urlBuilder.getSynchronizationPage(this.snapshot);
}
```

2021-09-21 04:11 UTC, louis-bompart approved these changes

2021-09-21 04:12 UTC, louis-bompart requested changes
The `print` method is really similar in the two classes, it might be good to refactor here :)

2021-09-21 16:30 UTC, louis-bompart approved these changes

2021-09-21 17:27 UTC, merged