chore(react): lock other react deps
coveo/cli pull request #744
Opened 2022-04-01 04:33 UTC by louis-bompart

## Proposed changes

Other dependencies are marked as a major update because they drop support for React 17. So we locked 'em up.

2022-04-01 04:33 UTC, louis-bompart commented
Fun fact: #742, my OG PR has been rejected... by the god darn bot.

2022-04-06 19:21 UTC, y-lakhdar approved these changes

2022-04-06 19:38 UTC, y-lakhdar requested changes
Oups, I approved too fast.
There is still a peer dependency with React to fix

2022-04-08 14:08 UTC, y-lakhdar approved these changes

2022-04-08 14:38 UTC, merged