fix(snapshot): reporter considers fixable reports for onSuccess callback
coveo/cli pull request #779
Opened 2022-05-03 06:04 UTC by louis-bompart

https://coveord.atlassian.net/browse/CDX-946

## Proposed changes

- Removed `isSuccessReport` method so that all usage fit the pattern of the snapshotReporter.
- Shift the last usage of the defunct method to the new pattern
- Fixed UT by removing unforeseen side-effect: because we were only mocking the return/resolved value of some function, they were sharing instances across tests. Mocking the implementation fixed that, by making sure the returned value of the mocked implementation is always 'fresh new'

## Testing

- [X] Unit Tests: refactored; I added a TODO for post GA to rewrite some big chunk of tests in preview and push, that's needed. I spent too much time on this PR because of the debt we accrued here.
- [x] Functionnal Tests: existing

2022-05-03 06:11 UTC, louis-bompart commented on packages/cli/src/lib/snapshot/snapshotReporter.ts
> +      statuses.successes.push(SnapshotReportStatus.SUCCESS);
This is bound to really evolve as we improve the error handling with better warnings, auto-fixes etc.

2022-05-03 16:33 UTC, y-lakhdar approved these changes
Nice.
discussed with Louis in Slack

2022-05-03 17:12 UTC, y-lakhdar requested changes
the e-fuse does not work

2022-05-04 18:12 UTC, olamothe approved these changes

2022-05-06 14:12 UTC, merged