feat(cli/cli-commons)!: Remove message from stopSpinner
coveo/cli pull request #949
Opened 2022-09-22 20:50 UTC by louis-bompart

## Proposed changes

- Remove `message` from the options of `stopSpinner`
- Remove the only usage
- Adapt E2E
- Fix the FIXME: `fancyIt` should not be used if no commands is instanciated. Instead, stderr-stdout should be used directly.

Motivation: From a UX perspective, the spinner in the CLI is used for 'Doing X, please wait'.
We don't need to say 'We've done X' after that, just to communicate the status of the operation. ✔️ and ❌ are perfect for that, so let's just use that and exclusively that.

## Breaking changes

Removed `message` from the options of `stopSpinner`.
It's technically a breaking change, sure we can consider that `@coveo/cli-commons` is so early that no one would be impacted. What I see here is the perfect excuse to test that the independent release works nice and proper ;)

## Testing

- [x] Unit Tests: adapted
- [x] Functional Tests: adapted

-----

⚠️  Should be merged with rebase strategy. ⚠️

2022-09-28 15:30 UTC, y-lakhdar requested changes
It's only working because of the test order. 
Need to consume first stderr before running the tests.

2022-09-29 16:10 UTC, y-lakhdar commented on packages/cli/commons/package.json
> +    "jest-mock-process": "^2.0.0",
Where is this used?

2022-09-30 02:31 UTC, louis-bompart commented on packages/cli/commons/package.json
> +    "jest-mock-process": "^2.0.0",
- [ ] uninstall `jest-mock-process`

2022-10-03 14:24 UTC, y-lakhdar approved these changes

2022-10-03 15:41 UTC, merged