feat: return resource types within project
coveo/cli pull request #952
Opened 2022-09-23 14:42 UTC by y-lakhdar

## Proposed changes

New method to retrieve all the resource types a project contains.
This will be particularly useful later when we will have to ensure the user has access to the resources before creating a snapshot.

I also rearranged the tests on the project.spec.ts file since it was getting very messy
## Testing

- [ ] Unit Tests:

- [ ] Functionnal Tests:

- [ ] Manual Tests:

2022-09-23 14:43 UTC, y-lakhdar commented on packages/cli/core/src/lib/project/project.spec.ts
> +          mockedFileDepthSearch.mockReturnValueOnce([
mocking FileDepthSearch instead of readDirSync

2022-09-23 16:43 UTC, y-lakhdar commented on packages/cli/core/src/lib/project/project.spec.ts
> +      '#compressResources should ensure resources folder exists',
Because the outer and inner describe were containing the same amount of tests. I think there were unnecessary describe blocks.

2022-09-23 17:05 UTC, louis-bompart requested changes
more UT

2022-09-23 17:05 UTC, louis-bompart commented on packages/cli/core/src/lib/project/project.spec.ts
> +      '#compressResources should ensure resources folder exists',
Good point, there are a bunch of tests that are missing, so:
 - [ ] revert the change of describe architecture for invalid project
 - [ ] test your changes with an invalid project (notably #resourceType)

2022-09-28 18:04 UTC, louis-bompart approved these changes

2022-10-03 17:07 UTC, merged